### ISSUE TITLE
Try-with-resources

### ISSUE THREAD

**Issue by ilgonmic** [facid/console_chat#3]
https://github.com/facid/console_chat/blob/893d8b87281b40263d3fe33c59444e2aac226dee/src/main/server/Server.java#L22

Don't use try only for closing some resources, use try-with-resources notation instead
https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

**Comment by facid** [comment]
Thanks, fixed

**Comment by CherniyFY** [comment]
Fixed in 9631e0cdc0048fd6bd2078d45c34bb97b4b48530
