### ISSUE TITLE
Boolean method

### ISSUE THREAD

**Issue by ilgonmic** [facid/console_chat#4]
https://github.com/facid/console_chat/blob/893d8b87281b40263d3fe33c59444e2aac226dee/src/main/server/Server.java#L43

`replaceAll` nullable?
```
if (true) return true
else false
```
Can be easier

**Comment by facid** [comment]
Fixed

**Comment by CherniyFY** [comment]
Fixed in 9631e0cdc0048fd6bd2078d45c34bb97b4b48530
