### ISSUE TITLE
Avoid static mutable objects

### ISSUE THREAD

**Issue by ilgonmic** [facid/console_chat#6]
https://github.com/facid/console_chat/blob/893d8b87281b40263d3fe33c59444e2aac226dee/src/main/server/MessageHistory.java#L9

Static methods are not bad, but they usually are util methods without side effects
In this case MessageHistory is good class, that can be implemented w/o static
(Yes, I know, that it was to avoid problems with multitreading, but it is good opportunity to learn synchronized :)

**Comment by facid** [comment]
Fixed

**Comment by CherniyFY** [comment]
Fixed in 9631e0cdc0048fd6bd2078d45c34bb97b4b48530
